- name: Install Apache HTTP Server
  become: yes
  yum:
    name: httpd
    state: present

- name: Start Apache HTTP Server
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes
